const $ = s => document.querySelector(s);
const icons = () => lucide.createIcons();
const icon = name => `<i data-lucide="${name}" aria-hidden="true"></i>`;
const btn = (name,label,action,cls='')=>`<button class="icon-button ${cls}" aria-label="${label}" title="${label}" data-action="${action}">${icon(name)}</button>`;
const safe = value => String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const contacts=[{id:'lin',name:'林间晚风',initial:'林',color:'mint',online:true,game:'Dota 2',preview:'今晚八点？我应该能准时上线',time:'14:32',unread:2},{id:'morrow',name:'Morrow',initial:'M',color:'rose',online:true,game:'Counter-Strike 2',preview:'图片已收到，画质不错',time:'14:18',unread:1},{id:'island',name:'小岛邮差',initial:'岛',color:'gold',online:true,game:'Stardew Valley',preview:'[图片] 给你看看我的新农场',time:'13:56',unread:0},{id:'north',name:'Northstar',initial:'N',color:'blue',online:false,preview:'好，那我们周末再约',time:'12:40',unread:0},{id:'white',name:'白噪音',initial:'白',color:'lilac',online:false,preview:'这次更新终于修好了',time:'昨天',unread:0}];
const sceneNames={inbox:'会话列表',chat:'文字、图片与表情',lock:'锁屏通知',settings:'通知与连接',server:'配置后端地址',login:'登录后台账户',friends:'好友'};
const sceneOrder=['inbox','chat','lock','settings','server','login'];
const requested=new URLSearchParams(location.search).get('screen');
const state={screen:sceneNames[requested]?requested:'inbox',active:'lin',connected:true,queued:[],notification:null,sequence:10,background:true,showPreview:true,sound:true,emojiTab:'steam',sheet:null,query:'',onlyUnread:false,draft:'',attachment:null,server:'https://chat.example.com',username:'orbit',authenticated:true};
const history={lin:[{id:1,kind:'text',text:'晚上要不要一起开黑？新活动看起来不错。',time:'14:28',self:false},{id:2,kind:'text',text:'好啊！我更新好了，随时可以。',time:'14:29',self:true},{id:3,kind:'image',src:'../prototype/assets/dota.jpg',text:'Dota 2',time:'14:30',self:false},{id:4,kind:'text',text:'今晚八点？我应该能准时上线',time:'14:31',self:false},{id:5,kind:'emote',src:'./assets/steamthumbsup.png',text:':steamthumbsup:',time:'14:32',self:true}],morrow:[{id:6,kind:'text',text:'图片已收到，画质不错',time:'14:18',self:false}],island:[{id:7,kind:'image',src:'../prototype/assets/stardew.jpg',text:'我的农场',time:'13:56',self:false}]};
const avatar=(c,cls='')=>`<span class="avatar ${c.color} ${cls}">${c.initial}${c.online?'<b class="online-dot"></b>':''}</span>`;
const contact=()=>contacts.find(c=>c.id===state.active);
function go(screen){state.screen=screen;state.sheet=null;state.query='';const url=new URL(location.href);url.searchParams.set('screen',screen);window.history.replaceState({},'',url);if(screen==='chat')contact().unread=0;render();}
function nav(){return `<nav class="bottom-nav">${[['inbox','messages-square','消息'],['friends','users','好友'],['settings','settings-2','设置']].map(([screen,i,label])=>`<button class="${state.screen===screen?'active':''}" data-screen="${screen}"><span>${icon(i)}${screen==='inbox'&&totalUnread()?`<b>${totalUnread()}</b>`:''}</span><small>${label}</small></button>`).join('')}</nav>`;}
function totalUnread(){return contacts.reduce((n,c)=>n+c.unread,0);}
function connection(){return `<button class="connection ${state.connected?'':'offline'}" data-screen="settings"><span class="dot"></span><span>${state.connected?'orbit · 已连接':'连接已断开 · 等待网络恢复'}</span>${icon('chevron-right')}</button>`;}
function listRows(){const rows=contacts.filter(c=>(!state.onlyUnread||c.unread||state.screen==='friends')&&c.name.toLowerCase().includes(state.query.toLowerCase()));return rows.length?rows.map(c=>`<button class="contact" data-contact="${c.id}">${avatar(c)}<span class="contact-body"><span class="contact-title"><strong>${c.name}</strong><time>${state.screen==='friends'?'':c.time}</time></span><span class="contact-preview"><span>${safe(state.screen==='friends'?(c.game?`正在玩 ${c.game}`:c.online?'在线':'离线'):c.preview)}</span>${state.screen!=='friends'&&c.unread?`<b>${c.unread}</b>`:''}</span></span></button>`).join(''):'<p class="empty">没有匹配的会话</p>';}
function inbox(){return `<header class="main-header"><div class="brand-line">${icon('gamepad-2')}<span>Steam Chat</span><span class="account-mini">O</span></div><div class="title-line"><h1>${state.screen==='friends'?'好友':'消息'}</h1>${btn('square-pen','新建会话','new-chat')}</div><label class="search">${icon('search')}<input type="search" aria-label="搜索好友和消息" placeholder="搜索好友" value="${safe(state.query)}"></label>${connection()}${state.screen==='inbox'?`<div class="list-tabs"><button data-filter="all" class="${!state.onlyUnread?'active':''}">全部消息</button><button data-filter="unread" class="${state.onlyUnread?'active':''}">未读 <span>${totalUnread()}</span></button></div>`:'<div class="friends-count">3 位在线 · 5 位好友</div>'}</header><div class="contact-list">${listRows()}</div>${nav()}`;}
function message(m){return `<div class="message ${m.self?'self':''}">${!m.self?avatar(contact(),'message-avatar'):''}<div class="message-stack">${m.kind==='text'?`<div class="bubble">${safe(m.text)}</div>`:m.kind==='image'?`<button class="image-message" data-image="${safe(m.src)}" aria-label="查看图片"><img src="${safe(m.src)}" alt="${safe(m.text)}"><span>${icon('expand')}</span></button>`:m.kind==='sticker'?`<div class="sent-sticker"><span>${safe(m.symbol)}</span><strong>${safe(m.text)}</strong></div>`:`<div class="emote-message"><img src="${m.src}" alt="${safe(m.text)}"></div>`}<span class="message-time">${m.time}${m.self?`${icon(m.pending?'clock-3':'check-check')}${m.pending?'等待网络':''}`:''}</span></div></div>`;}
function chat(){const c=contact();return `<header class="chat-header">${btn('arrow-left','返回消息列表','back')}${avatar(c,'small')}<div><h1>${c.name}</h1><p>${state.connected?(c.game?`正在玩 ${c.game}`:c.online?'在线':'离线'):'网络已断开'}</p></div>${btn('panel-right','好友资料','profile')}</header>${!state.connected?'<div class="offline-banner">连接中 · 消息将在网络恢复后发送</div>':''}<div class="thread-scroll"><div class="date-divider">今天 · 14:28</div>${(history[state.active]||[]).map(message).join('')}</div><footer class="composer">${state.attachment?`<div class="attachment-preview"><img src="${state.attachment}" alt="待发送图片">${btn('x','移除待发送图片','remove-photo')}<span>待发送图片</span></div>`:''}<div class="input-row"><textarea rows="1" placeholder="发送消息…" aria-label="消息内容">${safe(state.draft)}</textarea></div><div class="composer-tools"><div>${btn(state.sheet==='emoji'?'keyboard':'smile','表情与贴纸','emoji')}${btn('image','发送图片','photo')}</div><button class="send" data-action="send" aria-label="发送消息">${icon('arrow-up')}</button></div></footer>${state.sheet==='emoji'?emojiPanel():''}`;}
const emojis=['😀','😊','😂','🥰','😎','🤔','😮','😭','👍','👏','❤️','🎉','🔥','✨','🎮','☕'];
function emojiPanel(){return `<section class="emoji-panel" aria-label="表情面板"><div class="emoji-tabs"><button class="${state.emojiTab==='steam'?'active':''}" data-emotab="steam">Steam</button><button class="${state.emojiTab==='emoji'?'active':''}" data-emotab="emoji">Emoji</button><button class="${state.emojiTab==='stickers'?'active':''}" data-emotab="stickers">贴纸</button>${btn('x','关闭表情面板','close-sheet')}</div><div class="emoji-grid">${state.emojiTab==='steam'?['steamhappy','steamthumbsup'].map(name=>`<button data-emote="${name}" title=":${name}:"><img src="./assets/${name}.png" alt=":${name}:"></button>`).join(''):state.emojiTab==='emoji'?emojis.map(e=>`<button data-emoji="${e}">${e}</button>`).join(''):'<button class="sticker-tile" data-sticker="happy"><span>🎮</span><small>开黑走起</small></button><button class="sticker-tile" data-sticker="yes"><span>🙌</span><small>好耶！</small></button>'}</div></section>`;}
function settingToggle(name,title,description){return `<label class="setting-row"><span><strong>${title}</strong><small>${description}</small></span><input type="checkbox" role="switch" data-setting="${name}" ${state[name]?'checked':''}></label>`;}
function settings(){return `<header class="settings-header"><h1>设置</h1></header><div class="settings-scroll"><section class="account-section"><span class="my-avatar">O</span><div><h2>${safe(state.username)}</h2><p>当前 Steam 账户 · orbit</p></div>${icon('shield-check')}</section><h3 class="section-label">消息通知</h3><section class="settings-section">${settingToggle('background','后台接收消息','显示常驻连接通知')}${settingToggle('showPreview','通知显示消息内容','关闭后仅显示发送者')}${settingToggle('sound','消息提醒','接收新消息通知')}</section><h3 class="section-label">连接与设备</h3><section class="settings-section"><button class="setting-row" data-screen="server"><span><strong>后端地址</strong><small>${safe(state.server)}</small></span>${icon('chevron-right')}</button><button class="setting-row" data-action="connection-info"><span><strong>连接状态</strong><small>${state.connected?'WebSocket 已连接':'网络不可用'}</small></span><span class="status-label ${state.connected?'':'off'}">${state.connected?'在线':'离线'}</span></button><button class="setting-row" data-action="battery"><span><strong>后台运行设置</strong><small>荣耀 · MagicOS 10</small></span>${icon('chevron-right')}</button></section><div class="device-note">荣耀 WIN RT · Android 16</div><button class="logout-button" data-action="logout">退出登录</button></div>${nav()}`;}
function server(){return `<header class="setup-header">${btn('arrow-left','返回','back-settings')}<span>连接服务器</span></header><div class="setup-content"><div class="app-logo">${icon('gamepad-2')}</div><h1>你的 Steam Chat</h1><p class="setup-subtitle">连接后端，继续你的会话。</p><form id="server-form"><label>后端地址<div class="url-input">${icon('lock-keyhole')}<input type="url" name="server" value="${safe(state.server)}" placeholder="https://chat.example.com" required></div></label><p class="form-error" id="server-error"></p><button class="primary" type="submit">连接服务器 ${icon('arrow-right')}</button></form><div class="secure-note">${icon('shield-check')} HTTPS 安全连接</div></div><p class="setup-footer">Steam Chat for Android</p>`;}
function login(){return `<header class="setup-header">${btn('arrow-left','返回地址配置','setup')}<span>登录</span></header><div class="setup-content"><div class="app-logo">${icon('gamepad-2')}</div><h1>欢迎回来</h1><p class="setup-subtitle">${safe(state.server)}</p><form id="login-form"><label>后台账号<input name="username" autocomplete="off" value="orbit" required></label><label>演示密码<input name="password" type="password" autocomplete="off" placeholder="任意演示密码，请勿输入真实密码" required></label><button class="primary" type="submit">登录 ${icon('arrow-right')}</button></form><div class="secure-note">${icon('shield-check')} 后台账户登录</div></div><p class="setup-footer">Steam Chat for Android</p>`;}
function notificationCard(lock=false){const n=state.notification;return `<div class="message-notification ${lock?'lock-notification':''}"><div class="notification-app">${icon('gamepad-2')}<span>Steam Chat</span><small>现在</small></div><button class="notification-body" data-action="open-notification">${avatar(contacts[0],'small')}<span><strong>林间晚风</strong><p>${state.showPreview?safe(n?.text||'你收到一条新消息'):'你收到一条新消息'}</p></span>${icon('chevron-right')}</button><div class="notification-actions"><button data-action="open-notification">回复</button><button data-action="read-notification">标为已读</button></div></div>`;}
function lockScreen(){return `<div class="lock-screen"><div class="lock-clock"><span>9月7日 星期一</span><strong>14:32</strong><p>${icon('cloud-sun')} 26° · 多云</p></div><div class="lock-notifications">${state.notification?notificationCard(true):'<p class="no-notifications">暂无新通知</p>'}${state.background?`<div class="persistent-notification">${icon('radio')}<span><strong>Steam Chat ${state.connected?'已连接':'正在重连'}</strong><small>${state.connected?'后台接收消息中':'等待网络恢复'}</small></span>${icon('chevron-down')}</div>`:''}</div><button class="unlock" data-action="unlock">${icon('lock-keyhole')}打开 Steam Chat ${icon('arrow-up')}</button></div>`;}
function render(){const app=$('#app');app.className=`screen screen-${state.screen}`;app.innerHTML=state.screen==='inbox'||state.screen==='friends'?inbox():state.screen==='chat'?chat():state.screen==='settings'?settings():state.screen==='server'?server():state.screen==='login'?login():lockScreen();$('#notification').hidden=!state.notification||state.screen==='lock';$('#notification').innerHTML=state.notification&&state.screen!=='lock'?notificationCard():'';$('#screen-name').textContent=sceneNames[state.screen];$('#lab-network').textContent=state.connected?'已连接（模拟）':'已断开（模拟）';$('#lab-pending').textContent=state.queued.length;$('#lab-unread').textContent=totalUnread();$('#network-action-label').innerHTML=state.connected?'模拟断网<small>重连后补收消息</small>':'恢复网络<small>补收排队的消息</small>';icons();bindForms();if(state.screen==='chat')requestAnimationFrame(()=>{const s=$('.thread-scroll');s.scrollTop=s.scrollHeight;});console.info('Android prototype state',{screen:state.screen,connected:state.connected,queued:state.queued.length,unread:totalUnread(),background:state.background});}
function bindForms(){const search=$('.search input');if(search)search.oninput=e=>{state.query=e.target.value;$('.contact-list').innerHTML=listRows();icons();};const input=$('textarea');if(input)input.oninput=e=>state.draft=e.target.value;const sf=$('#server-form');if(sf)sf.onsubmit=e=>{e.preventDefault();try{const url=new URL(new FormData(sf).get('server'));if(url.protocol!=='https:'||url.username||url.password)throw Error();state.server=url.origin+url.pathname.replace(/\/$/,'');state.connected=true;go('login');}catch{$('#server-error').textContent='请输入不含账户密码的 HTTPS 地址';}};const lf=$('#login-form');if(lf)lf.onsubmit=e=>{e.preventDefault();state.username=String(new FormData(lf).get('username')).trim();lf.reset();state.authenticated=true;go('inbox');};}
function send(kind='text',payload){if(!state.draft.trim()&&!state.attachment&&!payload)return;const c=contact();const message={id:++state.sequence,kind, time:'14:33',self:true,pending:!state.connected};if(payload)Object.assign(message,payload);else if(state.attachment){message.kind='image';message.src=state.attachment;message.text='发送的图片';}else message.text=state.draft.trim();(history[c.id]??=[]).push(message);c.preview=message.kind==='image'?'[图片]':message.kind==='emote'?'[表情]':message.text;c.time='14:33';state.draft='';state.attachment=null;render();}
function incoming(){if(!state.authenticated){modal('尚未登录','<p class="guide">先完成演示登录，再模拟接收消息。</p>');return;}const message={id:++state.sequence,kind:'text',text:'我上线啦，准备好了叫我！',time:'14:33',self:false};if(!state.connected||(!state.background&&state.screen==='lock'))state.queued.push(message);else deliver(message);render();}
function deliver(message){if((history.lin||[]).some(m=>m.id===message.id))return;history.lin.push(message);contacts[0].preview=message.text;contacts[0].time='14:33';if(state.screen!=='chat'||state.active!=='lin'){contacts[0].unread++;if(state.sound)state.notification=message;}}
function toggleNetwork(){state.connected=!state.connected;if(state.connected&&(state.background||state.screen!=='lock')){const queue=state.queued.splice(0);queue.forEach(deliver);Object.values(history).flat().forEach(m=>m.pending=false);}render();}
function modal(title,body){$('.prototype-dialog')?.remove();const d=document.createElement('dialog');d.className='prototype-dialog';d.innerHTML=`<header><h2>${title}</h2><button class="icon-button" data-close>${icon('x')}</button></header>${body}`;document.body.append(d);d.querySelector('[data-close]').onclick=()=>d.close();d.onclick=e=>{if(e.target===d)d.close();};icons();d.showModal();return d;}
function photoSheet(){const d=modal('发送图片',`<div class="photo-choices"><button data-action="choose-file">${icon('image-plus')}从相册选择</button><button data-action="sample-photo"><img src="../prototype/assets/dota.jpg" alt="示例图片"><span>使用示例图片</span></button></div>`);}
function viewImage(src){const d=modal('图片',`<img class="full-image" src="${safe(src)}" alt="聊天图片">`);d.classList.add('image-dialog');}
document.addEventListener('click',e=>{const t=e.target.closest('button');if(!t)return;if(t.dataset.screen){go(t.dataset.screen);return;}if(t.dataset.contact){if(state.active!==t.dataset.contact){state.draft='';state.attachment=null;}state.active=t.dataset.contact;state.notification=null;go('chat');return;}if(t.dataset.filter){state.onlyUnread=t.dataset.filter==='unread';render();return;}if(t.dataset.image){viewImage(t.dataset.image);return;}if(t.dataset.emotab){state.emojiTab=t.dataset.emotab;render();return;}if(t.dataset.emoji){state.draft+=t.dataset.emoji;render();return;}if(t.dataset.emote){send('emote',{src:`./assets/${t.dataset.emote}.png`,text:`:${t.dataset.emote}:`});return;}if(t.dataset.sticker){send('sticker',{symbol:t.dataset.sticker==='happy'?'🎮':'🙌',text:t.dataset.sticker==='happy'?'开黑走起！':'好耶！'});return;}const action=t.dataset.action;if(!action)return;switch(action){case'back':state.notification=null;go('inbox');break;case'back-settings':go('settings');break;case'receive':incoming();break;case'lock':go('lock');break;case'unlock':if(state.connected)state.queued.splice(0).forEach(deliver);go(state.authenticated?'inbox':'login');break;case'network':toggleNetwork();break;case'setup':go('server');break;case'logout':state.authenticated=false;state.notification=null;go('login');break;case'new-chat':go('friends');break;case'emoji':state.sheet=state.sheet==='emoji'?null:'emoji';render();break;case'close-sheet':state.sheet=null;render();break;case'photo':photoSheet();break;case'choose-file':$('.prototype-dialog')?.close();$('#photo-input').click();break;case'sample-photo':$('.prototype-dialog')?.close();state.attachment='../prototype/assets/dota.jpg';state.sheet=null;render();break;case'remove-photo':state.attachment=null;render();break;case'send':send();break;case'open-notification':state.notification=null;state.active='lin';go('chat');break;case'read-notification':state.notification=null;contacts[0].unread=0;render();break;case'profile':{const c=contact();modal('好友资料',`<div class="friend-profile">${avatar(c,'large')}<h3>${c.name}</h3><p>${c.game?`正在玩 ${c.game}`:'离线'}</p><dl><dt>关系</dt><dd>Steam 好友</dd><dt>当前账户</dt><dd>orbit</dd></dl></div>`);break;}case'battery':modal('后台运行设置','<div class="guide"><p>原生 App 将引导完成以下设置：</p><ul><li>允许通知及锁屏通知</li><li>允许自启动与后台活动</li><li>不允许电池优化该应用</li><li>在最近任务中锁定 App</li></ul><p>这里不会修改系统设置。前台服务不能保证绕过系统休眠或强行停止。</p></div>');break;case'connection-info':modal('连接信息',`<div class="guide"><p>状态：${state.connected?'已连接':'已断开'}（模拟）</p><p>后端：${safe(state.server)}</p><p>待补收：${state.queued.length} 条</p></div>`);break;case'lab':{const d=modal('原型场景',`<div class="lab-actions"><button data-action="receive">模拟新消息</button><button data-action="lock">模拟锁屏</button><button data-action="network">${state.connected?'模拟断网':'恢复网络'}</button><button data-action="setup">首次配置</button></div><p class="guide">仅页面内演示，不会产生系统通知或连接后端。</p>`);d.querySelectorAll('[data-action]').forEach(b=>b.addEventListener('click',()=>d.close()));break;}}});
document.addEventListener('change',e=>{if(e.target.dataset.setting){state[e.target.dataset.setting]=e.target.checked;render();}});
$('#photo-input').onchange=e=>{const file=e.target.files?.[0];if(file&&file.type.startsWith('image/')){state.attachment=URL.createObjectURL(file);state.sheet=null;render();}e.target.value='';};
function cycle(delta){const i=sceneOrder.indexOf(state.screen);go(sceneOrder[(Math.max(0,i)+delta+sceneOrder.length)%sceneOrder.length]);}
$('#previous').onclick=()=>cycle(-1);$('#next').onclick=()=>cycle(1);
document.addEventListener('keydown',e=>{if(e.target.closest('input,textarea,[contenteditable]')||document.querySelector('dialog[open]'))return;if(e.key==='ArrowLeft'||e.key==='ArrowRight'){e.preventDefault();cycle(e.key==='ArrowLeft'?-1:1);}});
render();
